# Generated by Django 4.2.6 on 2023-11-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='items',
            field=models.ManyToManyField(through='app2.Cart_item', to='app2.product_data'),
        ),
    ]
