# Generated by Django 4.2.6 on 2023-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_cartmodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
